### PR TITLE
Hashing password

### PR DESCRIPTION
**Pull request by Angham116**
#31  done hashingPass function.

### CODE REVIEW

**Review by Fatmasiam — APPROVED** [review]

**Review by ahmedalmi95 — APPROVED** [review]

**Review by ahmedalmi95 — APPROVED** [review]
as a suggestion, to minimize your code you can use this, without create "gensalt": 
``` javascript
bcrypt.hash('myPassword', 10, (err, hash) => {
  // ..... dont forget convert it to promise
});
```

**Comment by kannanhassouna** [comment]
> as a suggestion, to shorten you can use like this :
> 
> ```js
> bcrypt.hash('myPassword', 10, (err, hash) => {
>   // .....
> });
> ```
#### If you want to use ``` getSalt, hash ``` : 
Another : 

```
const hashingPass = pass =>
  new Promise((resolve, reject) => {
    bc.genSalt(10, (err, salt) => {
      if (err) reject(err);
      bc.hash(pass, salt, (error, hashResult) => {
        if (err) reject(error);
        resolve(hashResult);
      });
    });
  });

```

**Comment by Angham116** [comment]
> > as a suggestion, to shorten you can use like this :
> > ```js
> > bcrypt.hash('myPassword', 10, (err, hash) => {
> >   // .....
> > });
> > ```
> 
> #### If you want to use `getSalt, hash` :
> Another :
> 
> ```
> const hashingPass = pass =>
>   new Promise((resolve, reject) => {
>     bc.genSalt(10, (err, salt) => {
>       if (err) reject(err);
>       bc.hash(pass, salt, (error, hashResult) => {
>         if (err) reject(error);
>         resolve(hashResult);
>       });
>     });
>   });
> ```

done.

**Review by Fatmasiam — APPROVED** [review]

**Review by ahmedalmi95 — APPROVED** [review]
:+1:

**Comment by tomduggan85** [comment]
Looks good 👍

**Review by Anies12 — APPROVED** [review]

**Comment by kannanhassouna** [comment]
really good job :+1:

**Review by kannanhassouna — APPROVED** [review]

**Pull request merged**
